############################## DQN PARAMS FOR PRETRAINING ##############################
do_pretrain: False
N_pretrain: [10000, 25000, 50000]
lr_schedule_pt: ''
save_ckpt_pretrained_model : 4
plot_inputs : False
############################## EXPLORATION ##############################
epsilon : 1  # greedy policy choice
min_eps_pct : 1.0 # decay for the epsilon parameter 0.1 linearly lead to 0.1n after 10 iter. 
min_eps : 0.5 # minimum possible value for epsilon
optimal_expl: False
alpha: 0.5
############################## PER BUFFER ##############################
use_PER : False
PER_e : 0.01  # Hyperparameter that we use to avoid some experiences to have 0 probability of being taken
PER_a : 0.6  # Hyperparameter that we use to make a tradeoff between taking only exp with high priority and sampling randomly
PER_b : 0.4   # importance-sampling, from initial value increasing to 1
PER_b_anneal : True
final_PER_b : 1.0
PER_b_steps : null
PER_a_anneal : False
final_PER_a : 1.0
PER_a_steps : null
sample_type : 'TDerror' #['TDerror', 'diffTDerror', 'rewards']
############################## RL RELATED ##############################
DQN_type : 'DDQN'
recurrent_env : False
gamma : 0.55 # discounting factor for the Q target (sort of interest rate)
kappa : 0.001 # risk aversion
std_rwds: False
max_exp_pct : 1.0
copy_step : 1
update_target : 'soft'
tau : 0.001
qts : [0.001,0.999] 
KLM :  [null, null, 25000] # [200000,40000,2000000]  # list with actions that each trade can take: from -K to +K lot sizes minimum size of tradable (equities/contracts) and discretization of holding for TabQ (-M,M) holding
zero_action : True
min_n_actions : False
RT : [0.050, 0.0001] # boundaries for returns and ticksize to define the discrete space of returns (only for TabQ)
tablr: 0.005 # learning rate for updating q table
############################## DL RELATED ##############################
selected_loss: 'huber'
activation : 'elu'
kernel_initializer : 'he_uniform'
optimizer_name : 'adam'
beta_1: 0.5
beta_2: 0.75
eps_opt: 0.1
hidden_units : [256,128]
batch_size : 256
learning_rate : 0.005 # 0.0003 as suggested by Karphaty
lr_schedule : 'exponential'
exp_decay_pct : 0.30
exp_decay_rate : 0.6
hidden_memory_units:  
unfolding: 1
############################## REGULARIZATION ##############################
batch_norm_input : True # bool to decide if add batch norm to input layer or not
batch_norm_hidden : False
clipgrad : ''
clipnorm : 1.0
clipvalue : 1.0
clipglob_steps: 50000
############################## DATA SIMULATIONS PARAMETERS ##############################
datatype: 'garch_mr' # real,garch,t_stud,t_stud_mfit, garch_mr
factor_lb: [[36],[32],[43]] #[[55],[1]]
CostMultiplier: 0.001 # Cost multiplier to make the cost proportional to the risk as in Gar Ped (2013)
                          # It is chosen as the median across the estimate of CM for each asset
discount_rate: 0.0 # discount rate as in the paper
Startholding: 0.0
############################## data parameters for GARCH simulation ##############################
mean_process: 'AR'
lags_mean_process : 1
vol_process : 'GARCH' #['GARCH', 'TGARCH', 'EGARCH', 'Constant']
distr_noise :  'normal' #['normal', 'studt', 'skewstud', 'ged']
############################## data parameters for realdata ##############################
symbol: null
############################## data parameters for GP like simulation ##############################
HalfLife : [350] #[2.5, 126.0, 630.0]
f0 : [0] # initial values for simulating factors
f_param : [0.00535] # [0.00535, 0.005775, -0.005625] #[0.0214, 0.0231, -0.0225]  #  #0.01 #[0.01, 0.0231, -0.04250] # regression parameters for factors [10.32,122.34,-205.59]
sigma  : 0.01 # return volatility
sigmaf : [0.2] # [0.2, 0.1, 0.05] # [0.59, 0.059, 0.023] 
uncorrelated : True
degrees : [6,8]
#########################################################################################################
# LAUNCH SIMULATIONS
start_train : 1000
seed : [573,   6, 446, 122, 535, 169, 6554, 65453]
seedparam : 888
N_train : 300000  # training steps (each step consists of one action-value update)
out_of_sample_test : False
N_test: 10000
executeDRL: 1 # boolean to decide if run DRL agent
executeRL: 0 # boolean to decide if run RL agent
executeGP: 1 # boolean to decide if run GP solution
executeMV: 0 # boolean to decide if run MV solution
save_results: 0 # boolean to decide if save dataframe of results
save_table: 0
plot_hist: 0 # boolean to decide if plot weight histogram distribution (reduce size of tb logs)
plot_steps_hist : 20000
plot_steps: 1000 # steps for diagnostics on tensorboard
pdist_steps: 5000
save_model: 1 # save trained tf model
save_ckpt_model: 75
use_GPU : True
#########################################################################################################
# FOLDER PARAMETERS
runtype: 'multi' # single, multi
# Parameter for storing results
outputDir: 'outputs'
outputClass: 'DQN'
outputModel: '20210203_GARCH_MR' # choose model name as number of factors + varying parameter
varying_pars: ['factor_lb','seed'] #['HalfLife', 'f0', 'f_param', 'sigmaf'] # choose a parameter to vary while performing several different experiment
 # leave blank if you don't want to vary any parameter (no subfolder will be created) #['HalfLife','f0', 'f_param', 'sigmaf']
varying_type : 'chunk'
num_rnd_search : 8
##########################################################################################################
