# Possible choices for the plot type parameter are:
# 'metrics' 
# 'value'
# 'policy' 
# 'holding' 
# 'diagnostics'
# In this one one could reproduce similar figures to the paper and the supplementary material,
# as long as the folder path in the list "outputModel" contains relevant experiment to plot
# MULTI TEST OOS PARAMS
############################### LAUNCH SIMULATIONS ##############################
n_seeds : 250 # Number of OOS test to perform for each agent at each checkpoint
cores: 3
random_state : 9071 #[593, 373, 788, 833, 745]  #324 #9071 #9071 seed for two pos # 556785 seed for two neg # 33  # Seed for experiment reproducibility OOS. Used to draw "n_seeds" for OOS testing
use_GPU : False
varying_type : 'chunk'
varying_pars: ['outputModel'] 
#########################################################################################################
# COLORS
color_res : 'tab:blue'
color_mfree : 'tab:green'
color_gp : 'tab:orange'
#########################################################################################################
# FOLDER PARAMETERS
algo :  ['PPO']
plot_type: 'metrics_is' #'metrics_is' #'multi_policy' 
fullpath : False
generate_plot : False
optimal : True
policy_func : 'alpha' #alpha or time
holding: [0,  1e+2,1e+4, 1e+6, 1e+8] #[0,  1e+2,1e+3, 1e+4,1e+5, 1e+6,1e+7] #[-1e+8,-1e+7, -1e+4, 0, 1e+4, 1e+7,1e+8] #-5e+6 #null #5000.0 # null #0.3e+5
time_to_stop :  [1199,500,250,100] # [1199, 1000, 700,500,250, 100, 20] #0
alpha: 0.003 #0.003
outputDir: 'outputs'
outputClass: 'PPO'
seed : '24' #'24' #'959' # ['893','602'] #['178','317'] #'32764' 
var_plots : [
    # "NetPnl_OOS_{}_{}.parquet.gzip",
    # "Reward_OOS_{}_{}.parquet.gzip",
    # "SR_OOS_{}_{}.parquet.gzip",
    # "PnLstd_OOS_{}_{}.parquet.gzip",
    # "Pdist_OOS_{}_GP.parquet.gzip",
    # "AbsNetPnl_OOS_{}_{}.parquet.gzip",
    'AbsRew_OOS_{}_{}.parquet.gzip',
    # 'AbsRew_IS_{}_{}.parquet.gzip',
    # 'AbsWealth_OOS_{}_{}.parquet.gzip',
    # "AbsHold_OOS_{}_{}.parquet.gzip",
    # 'AbsSR_OOS_{}_{}.parquet.gzip',
    ]
    
var_plot_diagnostics : ['entropy_hist.npy', 'std_hist.npy']

n_dqn: null #'300000'
experiment_dqn: 'n_train_{}_halflife_{}_sigmaf_{}_mv_res_{}_inp_type_{}_seed_{}' 
hyperparams_model_dqn: null #['500000','66_630', '0.2_0.1'] #['500000','66_630', '0.1_0.1'] #['250000','126', '0.1'] #
hyperparams_exp_dqn: null #['250000','2.5', '0.2', 'False', 'f'] # for policy and value type of plot
outputModel_dqn: '20210503_GPGAUSS_1f_n_train_{}_halflife_{}_sigmaf_{}_mv_res_{}_inp_type_{}'
outputModels_dqn: ['20211101_DQNGARCH_pickseeds']

N_test: 1200 #1500 #200 # Length of OOS test
stochastic: False
window: 1 #150 #250 # 25
load_rewards: False
mv_solution: True
load_holdings: False
modeltag: '20211118_fixconv_residual_multi100'
dist_to_plot: 'r' # r or w for reward or wealth
ep_ppo: #2000 #1200 #3000 #1000 #1000 #800 #10 #2200 #2000 #4400 #5800 #6400 #1800 #3000 #3200 #4400 #4200 #7000 #[4000,2000] 
outputModel_ppo: '20221007_GP_1f_activation_relu' # '20221006_GP_1f_augadv_False_action_type_GPext_qts_0.001_0.999_0.0' #'20220607_convergence_augadv_True_mv_res_False' # '20220614_convergence_augadv_False_mv_res_True' #'20220607_convergence_augadv_True_mv_res_False' #'20220607_convergence_augadv_True_mv_res_False' #'20220607_convergence_augadv_False_mv_res_True' #'20220607_convergence_augadv_True_mv_res_False' # '20220603_convergence_reg_no_augdiv' #'20220208_convergence_mfree_lr_0.0009_batch_size_500' #'20220112_convergence_res_len_series_1200_halflife_240'
experiment_ppo: 'activation_relu_seed_842' #'augadv_False_action_type_GPext_qts_0.001_0.999_0.0_seed_842' #'augadv_False_mv_res_True_seed_346' #'augadv_True_mv_res_False_seed_24' # ['seed_24'] #['eta1_{}_eta2_0.001_seed_24'] #['lr_0.0009_batch_size_500_seed_24'] #['len_series_1200_halflife_240_seed_959'] #,'halflife_40_kappa_1e-05_seed_315'] #'mv_res_True_lr_0.0005_seed_893' #['mv_res_True_double_noise_{}_sigmaf_{}_lr_0.0005_seed_178','seed_317'] #'['mv_res_True_double_noise_{}_sigmaf_{}_lr_0.0005_seed_178','seed_317'] #,'mv_res_False_double_noise_{}_sigmaf_{}_lr_0.00025_seed_687'] #'mv_res_True_lr_0.0005_seed_178' #'mv_res_False_lr_0.0001_seed_687'] #'mv_res_False_lr_0.0001_seed_{}' #mv_res_True_lr_0.0005_seed_{}'
hyperparams_model_ppo: [0.0003] #['32_32'] #[0.99,0.98,'64_64','128_64'] #[False,None]  #[True,1e-05] #[True,1e-05] #[False,None] 
hyperparams_exp_ppo:  [0.0001]  #[True,1e-05]
outputModels_ppo:     [   '20221007_GP_1f_mvpen_mv_penalty_coef_5e-08'
   , '20221007_GP_1f_mvpen_mv_penalty_coef_1e-09'
   , '20221007_GP_1f_mvpen_mv_penalty_coef_1e-10']



  # [ '20221007_GP_1f_mvpen_mv_penalty_coef_1e-05'
  # , '20221007_GP_1f_mvpen_mv_penalty_coef_1e-06'
  # , '20221007_GP_1f_mvpen_mv_penalty_coef_1e-07'
   # , '20221007_GP_1f_mvpen_mv_penalty_coef_1e-08'
   # , '20221007_GP_1f_mvpen_mv_penalty_coef_1e-09'
   # , '20221007_GP_1f_mvpen_mv_penalty_coef_1e-10'
  # , '20221007_GP_1f_mvpen_mv_penalty_coef_1e-11'
  # , '20221007_GP_1f_mvpen_mv_penalty_coef_5e-05'
  # , '20221007_GP_1f_mvpen_mv_penalty_coef_5e-06'
  # , '20221007_GP_1f_mvpen_mv_penalty_coef_5e-07'
  # , '20221007_GP_1f_mvpen_mv_penalty_coef_5e-08'
  # , '20221007_GP_1f_mvpen_mv_penalty_coef_5e-09'
  # , '20221007_GP_1f_mvpen_mv_penalty_coef_5e-10'
  # , '20221007_GP_1f_mvpen_mv_penalty_coef_5e-11']


 # ['20221007_GP_1f_moreseeds']


# ['20221007_GP_1f_activation_linear', '20221007_GP_1f_activation_relu', '20221007_GP_1f_activation_tanh']


# ['20221006_GP_1f_augadv_False_action_type_GP_qts_0.001_0.999_0.0'
#  , '20221006_GP_1f_augadv_False_action_type_GP_qts_0.0_1.0_0.0'
#  , '20221006_GP_1f_augadv_False_action_type_GPext_qts_0.001_0.999_0.0'
#  , '20221006_GP_1f_augadv_False_action_type_GPext_qts_0.0_1.0_0.0'
#  , '20221006_GP_1f_augadv_False_action_type_MV_qts_0.001_0.999_0.0'
#  , '20221006_GP_1f_augadv_False_action_type_MV_qts_0.0_1.0_0.0'
  # , '20221006_GP_1f_augadv_True_action_type_GP_qts_0.001_0.999_0.0'
  # , '20221006_GP_1f_augadv_True_action_type_GP_qts_0.0_1.0_0.0'
  # , '20221006_GP_1f_augadv_True_action_type_GPext_qts_0.001_0.999_0.0'
  # , '20221006_GP_1f_augadv_True_action_type_GPext_qts_0.0_1.0_0.0'
  # , '20221006_GP_1f_augadv_True_action_type_MV_qts_0.001_0.999_0.0'
  # , '20221006_GP_1f_augadv_True_action_type_MV_qts_0.0_1.0_0.0']


# ['20221005_GP_1f_risk_reward_type_mean_var_kappa_0.0001'
#  , '20221005_GP_1f_risk_reward_type_mean_var_kappa_0.0005'
#  , '20221005_GP_1f_risk_reward_type_mean_var_kappa_0.001'
#  , '20221005_GP_1f_risk_reward_type_mean_var_kappa_0.005'
#  , '20221005_GP_1f_risk_reward_type_mean_var_kappa_0.01'
#  , '20221005_GP_1f_risk_reward_type_mean_var_kappa_0.05'
#  , '20221005_GP_1f_risk_reward_type_mean_var_kappa_0.1'
#  , '20221005_GP_1f_risk_reward_type_mean_var_kappa_0.5'
#  , '20221005_GP_1f_risk_reward_type_mean_var_kappa_1e-05'
#  , '20221005_GP_1f_risk_reward_type_mean_var_kappa_5e-05'
  # , '20221005_GP_1f_risk_reward_type_mean_var_kr_kappa_0.0001'
  # , '20221005_GP_1f_risk_reward_type_mean_var_kr_kappa_0.0005'
  # , '20221005_GP_1f_risk_reward_type_mean_var_kr_kappa_0.001'
  # , '20221005_GP_1f_risk_reward_type_mean_var_kr_kappa_0.005'
  # , '20221005_GP_1f_risk_reward_type_mean_var_kr_kappa_0.01'
  # , '20221005_GP_1f_risk_reward_type_mean_var_kr_kappa_0.05'
  # , '20221005_GP_1f_risk_reward_type_mean_var_kr_kappa_0.1'
  # , '20221005_GP_1f_risk_reward_type_mean_var_kr_kappa_0.5'
  # , '20221005_GP_1f_risk_reward_type_mean_var_kr_kappa_1e-05'
  # , '20221005_GP_1f_risk_reward_type_mean_var_kr_kappa_5e-05']








 # ['20221005_GP_1f_halflife_120', '20221005_GP_1f_halflife_240', '20221005_GP_1f_halflife_400', '20221005_GP_1f_halflife_60']

# [ '20221002_GP_1f_lr_0.0003_batch_size_500']




# ['20221002_GP_1f_lr_0.0001_batch_size_100'
#  , '20221002_GP_1f_lr_0.0001_batch_size_250'
#  , '20221002_GP_1f_lr_0.0001_batch_size_500'
#  , '20221002_GP_1f_lr_0.0003_batch_size_100'
#  , '20221002_GP_1f_lr_0.0003_batch_size_250'
#  , '20221002_GP_1f_lr_0.0003_batch_size_500'
#  , '20221002_GP_1f_lr_0.0005_batch_size_100'
#  , '20221002_GP_1f_lr_0.0005_batch_size_250'
#  , '20221002_GP_1f_lr_0.0005_batch_size_500'
#  , '20221002_GP_1f_lr_0.00075_batch_size_100'
#  , '20221002_GP_1f_lr_0.00075_batch_size_250'
#  , '20221002_GP_1f_lr_0.00075_batch_size_500'
#  , '20221002_GP_1f_lr_0.0015_batch_size_100'
#  , '20221002_GP_1f_lr_0.0015_batch_size_250'
#  , '20221002_GP_1f_lr_0.0015_batch_size_500'
#  , '20221002_GP_1f_lr_0.001_batch_size_100'
#  , '20221002_GP_1f_lr_0.001_batch_size_250'
#  , '20221002_GP_1f_lr_0.001_batch_size_500']