# MULTI TEST OOS PARAMS
############################### LAUNCH SIMULATIONS ##############################
N_test: 500 # Length of OOS test
n_seeds : 10 # Number of OOS test to perform for each agent at each checkpoint
random_state : 4532345  # Seed for experiment reproducibility OOS. Used to draw "n_seeds" for OOS testing
use_GPU : True
varying_type : 'chunk'
varying_pars: ['outputModel'] 
num_rnd_search : 4 # number of parallelized OOS test to perform
parbyseed : True # Choose if parallelize by seeds. 
                 # If False the parallelization will be done through folders as specified in "varying_pars"
#########################################################################################################
# FOLDER PARAMETERS
outputDir: 'outputs'
outputClass: 'DQN'
outputModel:   ['20210410_GPSTUD_3f_datatype_garch_MV_res_False', 
  '20210410_GPSTUD_3f_datatype_garch_MV_res_True']


# ['20210409_GPGAUSS_2f_ret_HalfLife_115_350_CostMultiplier_0.001', 
#  '20210409_GPGAUSS_2f_ret_HalfLife_115_350_CostMultiplier_0.01', 
#  '20210409_GPGAUSS_2f_ret_HalfLife_200_1260_CostMultiplier_0.001', 
#  '20210409_GPGAUSS_2f_ret_HalfLife_200_1260_CostMultiplier_0.01', 
#  '20210409_GPGAUSS_2f_ret_HalfLife_50_250_CostMultiplier_0.001', 
#  '20210409_GPGAUSS_2f_ret_HalfLife_50_250_CostMultiplier_0.01'] 


# ['20210410_GPSTUD_3f_datatype_t_stud_MV_res_False', 
#    '20210410_GPSTUD_3f_datatype_t_stud_MV_res_True']





# ['20210408_GPGAUSS_3f_CostMultiplier_0.01_MV_res_False', 
#   '20210408_GPGAUSS_3f_CostMultiplier_0.01_MV_res_True'] 
#   '20210408_GPGAUSS_3f_CostMultiplier_0.01_MV_res_False', 
#   '20210408_GPGAUSS_3f_CostMultiplier_0.01_MV_res_True', 
#   '20210408_GPGAUSS_3f_CostMultiplier_0.1_MV_res_False', 
#   '20210408_GPGAUSS_3f_CostMultiplier_0.1_MV_res_True', 
#   '20210408_GPGAUSS_3f_CostMultiplier_0.5_MV_res_False', 
#   '20210408_GPGAUSS_3f_CostMultiplier_0.5_MV_res_True']


# ['20210330_GPGAUSS_testMVresidual1'] 
# length : '100k' # string representing the length of experiment folder to plot
algo :  ['DQN'] # list of algorithm to plot their results. 'DQN' and 'Q' as possible values
plot_type: 'pnlsrgauss' 
# Possible choices for this last parameter are:
# 'pnlsrgauss' (Figure 1 paper)
# 'pnlsrstud' (Figure 3 paper)
# 'pnlsrgarch' (Figure 4 paper)
# 'policies' (Figure 2 paper)
# 'holdings' (Figure 5 paper)
# 'rewgauss' (Figure 1 supplementary material)
# 'rewstud' (Figure 2 supplementary material)
# 'rewgarch' (Figure 3 supplementary material)
# 'ppo' (Figure 1 rebuttal)
# In this one one could reproduce similar figures to the paper and the supplementary material,
# as long as the folder path in the list "outputModel" contains relevant experiment to plot
