# MULTI TEST OOS PARAMS
############################### LAUNCH SIMULATIONS ##############################
random_state : 4567  # Seed for experiment reproducibility OOS 
N_test: 5000
n_seeds : 10
plot_lr : False
plot_experience : False
plot_buffer : False
conf_interval: False
use_GPU : True
#########################################################################################################
# FOLDER PARAMETERS
outputDir: 'outputs'
outputClass: 'DQN'
outputModel: ['20210210_GPGAUSS_decouple_discretization_None_temp_100.0', 
'20210210_GPGAUSS_decouple_discretization_None_temp_50.0',
'20210209_GPGAUSS_decouple_side_only_True',
'20210209_GPGAUSS_decouple_side_only_False']



 # ['20210211_GPGAUSS_decouple_bcm_bcm_scale_0.0001']#, '20210211_GPGAUSS_decouple_bcm_bcm_scale_0.001']
 # '20210211_decoupl_symbol_BRK.A_side_only_False', '20210211_decoupl_symbol_BRK.A_side_only_True']



# ['20210208_real_3act_symbol_BRK.A','20210208_real_symbol_BRK.A']

length : '300k'
algo :  ['DQN'] #['DQN','Q']
gen_test : True
gen_plot : False
parbyseed : True
varying_pars: ['outputModel'] 
varying_type : 'chunk'
num_rnd_search : 8
plot_type: 'holdings'

# GAUSS
# ['20210107_GPGAUSS_final', '20210108_GPGAUSS_2f_final']
# STUD
# ['20210107_GPSTUDmfit_final','20210108_GPSTUDfullfit_final',
#               '20210108_GPSTUD_df8_final_datatype_t_stud_mfit', '20210108_GPSTUD_df8_final_datatype_t_stud']
# GARCH
# ['20210109_GARCH_long_distr_noise_normal', '20210109_GARCH_long_distr_noise_studt']
# ['20210108_GARCH_final_distr_noise_normal','20210108_GARCH_final_distr_noise_studt',
# '20210109_EGARCH','20210109_EGARCH_studt']
# GARCH MR
# ['20210202_GARCH_MR_correct_factor_lb_32', '20210202_GARCH_MR_correct_factor_lb_36', '20210202_GARCH_MR_correct_factor_lb_43']