# Flags for operate different tests
algo : 'Qlin' # Q: Qlearning experiment from Ritter(2017), Qlin: Extentions to lin approxim
# Parameter for the QLearning implementation of Ritter
epsilon : 0.1  # greedy policy choice
alpha : 0.001 # discounting factor for the Q updating error (learning rate)
gamma : 0.999 # discounting factor for the Q target (sort of interest rate)
kappa : 0.0001 # risk aversion
HalfLife  : 5 # half-life of mean reversion to compute speed of mean reversion
sigma  : 0.1 # asset volatility
P_min  : 1 # boundaries of the price
P_max  : 1000
P_e    : 50.0 # equilibrium price
LotSize  : 100 # minimum size of tradable (equities/contracts)
K  : 500 # actions that each trade can take: from -K to +K lot sizes
M  : 1000 # multiple of lot Sizes than the total portfolio can hold
TickSize  : 0.1 # minimum price movement of a trading instrument
N_train : 100000 # training steps (each step consists of one action-value update)
TestSteps: 5000 # Out-of-sample simulated price for testing
##########################################################################################################
# Parameter for extending the framework
CostMultiplier: 1 # Cost multiplier to test the agent in different liquidity regimes
Seed: 42 # Seed for experiment reproducibility
RollingMean: False # Flag for calculating the rolling mean of expected returns
LenRollMean: 66 # Lenght of the rolling mean of expected returns (default 3 months)
##########################################################################################################
# Parameter for storing results
outputDir: 'RitterLinear'
##########################################################################################################
# Parameter for plotting results
holding: 0 # set holding to visualize
Aggregation: 1 # flag for aggregation by holding
##########################################################################################################
# Parameter for linear q-function approximation