# MULTI TEST OOS PARAMS
############################### LAUNCH SIMULATIONS ##############################
N_test: 100 # Length of OOS test
n_seeds : 2 # Number of OOS test to perform for each agent at each checkpoint
random_state : 4567  # Seed for experiment reproducibility OOS. Used to draw "n_seeds" for OOS testing
use_GPU : True
varying_type : 'chunk'
varying_pars: ['outputModel'] 
num_rnd_search : 2 # number of parallelized OOS test to perform
parbyseed : True # Choose if parallelize by seeds. 
                 # If False the parallelization will be done through folders as specified in "varying_pars"
#########################################################################################################
# FOLDER PARAMETERS
outputDir: 'outputs'
outputClass: 'PPO'
outputModel: ['20210328_PPO_final','20210328_PPO_misspec_final']
length : '1_2M' # string representing the length of experiment folder to plot
algo :  ['PPO'] # list of algorithm to plot their results. 'DQN' and 'Q' as possible values
plot_type: 'ppo' 
# Possible choices for this last parameter are:
# 'pnlsrgauss' (Figure 1 paper)
# 'pnlsrstud' (Figure 3 paper)
# 'pnlsrgarch' (Figure 4 paper)
# 'policies' (Figure 2 paper)
# 'holdings' (Figure 5 paper)
# 'rewgauss' (Figure 1 supplementary material)
# 'rewstud' (Figure 2 supplementary material)
# 'rewgarch' (Figure 3 supplementary material)
# 'ppo' (Figure 1 rebuttal)
# In this one one could reproduce similar figures to the paper and the supplementary material,
# as long as the folder path in the list "outputModel" contains relevant experiment to plot
