# Possible choices for the plot type parameter are:
# 'metrics' 
# 'value'
# 'policy' 
# 'holding' 
# 'diagnostics'
# In this one one could reproduce similar figures to the paper and the supplementary material,
# as long as the folder path in the list "outputModel" contains relevant experiment to plot
# MULTI TEST OOS PARAMS
############################### LAUNCH SIMULATIONS ##############################
n_seeds : 250 # Number of OOS test to perform for each agent at each checkpoint
cores: 3
random_state : 9071 #[593, 373, 788, 833, 745]  #324 #9071 #9071 seed for two pos # 556785 seed for two neg # 33  # Seed for experiment reproducibility OOS. Used to draw "n_seeds" for OOS testing
use_GPU : False
varying_type : 'chunk'
varying_pars: ['outputModel'] 
#########################################################################################################
# COLORS
color_res : 'tab:blue'
color_mfree : 'tab:green'
color_gp : 'tab:orange'
#########################################################################################################
# FOLDER PARAMETERS
algo :  ['PPO']
fullpath : False
generate_plot : False
optimal : True
policy_func : 'alpha' #alpha or time
holding: [0, -1e+6, +1e+6] #, 1e+6, -1e+6] #[0, -1e+5, -1e+5, 1e+6, -1e+6]  #[0,  1e+2,1e+4,1e+5, 1e+6] # [0, -1e+2,-1e+4,-1e+5, -1e+6] #[0,  1e+2,1e+3, 1e+4,1e+5, 1e+6,1e+7] #[-1e+8,-1e+7, -1e+4, 0, 1e+4, 1e+7,1e+8] #-5e+6 #null #5000.0 # null #0.3e+5
time_to_stop :  [1199,100] # [1199, 1000, 700,500,250, 100, 20] #0
alpha: 0.003 #0.003
outputDir: 'outputs'
outputClass: 'PPO'
seed : '24' #'24' #'959' # ['893','602'] #['178','317'] #'32764' 
var_plots : [
    # "NetPnl_OOS_{}_{}.parquet.gzip",
    # "Reward_OOS_{}_{}.parquet.gzip",
    # "SR_OOS_{}_{}.parquet.gzip",
    # "PnLstd_OOS_{}_{}.parquet.gzip",
    # "Pdist_OOS_{}_GP.parquet.gzip",
    # "AbsNetPnl_OOS_{}_{}.parquet.gzip",
    'AbsRew_OOS_{}_{}.parquet.gzip',
    # 'AbsRew_IS_{}_{}.parquet.gzip',
    # 'AbsWealth_OOS_{}_{}.parquet.gzip',
    # "AbsHold_OOS_{}_{}.parquet.gzip",
    # 'AbsSR_OOS_{}_{}.parquet.gzip',
    ]
    
var_plot_diagnostics : ['entropy_hist.npy', 'std_hist.npy']

n_dqn: null #'300000'
experiment_dqn: 'n_train_{}_halflife_{}_sigmaf_{}_mv_res_{}_inp_type_{}_seed_{}' 
hyperparams_model_dqn: null #['500000','66_630', '0.2_0.1'] #['500000','66_630', '0.1_0.1'] #['250000','126', '0.1'] #
hyperparams_exp_dqn: null #['250000','2.5', '0.2', 'False', 'f'] # for policy and value type of plot
outputModel_dqn: '20210503_GPGAUSS_1f_n_train_{}_halflife_{}_sigmaf_{}_mv_res_{}_inp_type_{}'
outputModels_dqn: ['20211101_DQNGARCH_pickseeds']
N_test: 1200 #1500 #200 # Length of OOS test
stochastic: False
window: 1 #150 #250 # 25
load_rewards: False
mv_solution: True
load_holdings: False
modeltag: '20211118_fixconv_residual_multi100'
dist_to_plot: 'r' # r or w for reward or wealth
ep_ppo: 'best'
outputModel_ppo: '20230327_GP_test_2corrassets' #'20230218_GP_with_costs2_costmultiplier_0.1' #'20221223_GP_tune_hidden_units_actor_20_20_20_activation_tanh' #'20221203_GP_nocost_gaussian_clipping_3.4_halflife_120_sigmaf_0.01' #'20221129_GP2_f_param_0.0025_costmultiplier_9e-10' #'20221113_GP_clip_gaussian_clipping_3' #'20221118_GP_longer_f_param_0.01' #'20221113_GP_clip_gaussian_clipping_3' #'20221108_GP_linear2' #'20221104_GP_resc2_tanh_stretching_0.3'
experiment_ppo: 'seed_325' #'hidden_units_actor_20_20_20_activation_tanh_seed_885' 
hyperparams_model_ppo: [50.0] #['32_32'] #[0.99,0.98,'64_64','128_64'] #[False,None]  #[True,1e-05] #[True,1e-05] #[False,None] 
hyperparams_exp_ppo:  [1.5]  #[True,1e-05]
plot_type: 'metrics_is' #'metrics_is' #'multi_policy' #'holding'
outputModels_ppo: [  '20230414_GP_univ_lr_5e-05_epochs_10', 
  '20230414_GP_univ_lr_5e-05_epochs_3', 
  '20230414_GP_univ_lr_5e-05_epochs_5']
 
 
# [ '20230414_GP_univ_lr_0.0006_epochs_10', 
#  '20230414_GP_univ_lr_0.0006_epochs_3', 
#  '20230414_GP_univ_lr_0.0006_epochs_5', 
#  '20230414_GP_univ_lr_0.0009_epochs_10', 
#  '20230414_GP_univ_lr_0.0009_epochs_3', 
#  '20230414_GP_univ_lr_0.0009_epochs_5', 
  # '20230414_GP_univ_lr_5e-05_epochs_10', 
  # '20230414_GP_univ_lr_5e-05_epochs_3', 
  # '20230414_GP_univ_lr_5e-05_epochs_5']
 
 
 
 
 
 