# Possible choices for the plot type parameter are:
# 'metrics' 
# 'value'
# 'policy' 
# 'holding' 
# In this one one could reproduce similar figures to the paper and the supplementary material,
# as long as the folder path in the list "outputModel" contains relevant experiment to plot
# MULTI TEST OOS PARAMS
############################### LAUNCH SIMULATIONS ##############################
N_test: 500 # Length of OOS test
n_seeds : 3 # Number of OOS test to perform for each agent at each checkpoint
random_state : 4532345  # Seed for experiment reproducibility OOS. Used to draw "n_seeds" for OOS testing
use_GPU : True
varying_type : 'chunk'
varying_pars: ['outputModel'] 
#########################################################################################################
# FOLDER PARAMETERS
algo :  ['PPO']
plot_type: 'metrics' 
experiment: 'len_series_4000_seed_26' #'n_train_{}_halflife_{}_sigmaf_{}_mv_res_{}_inp_type_{}_seed_{}'
seed : '26'
optimal : True
outputDir: 'outputs'
outputClass: 'PPO'
outputModel: [ '20210427_GPGAUSS_tot_sens_mv_res_True_inp_type_f', 
 '20210427_GPGAUSS_tot_sens_mv_res_True_inp_type_ret']


# ['20210427_GPGAUSS_tot_sens_mv_res_False_inp_type_f', 
#  '20210427_GPGAUSS_tot_sens_mv_res_False_inp_type_ret', 
#  '20210427_GPGAUSS_tot_sens_mv_res_True_inp_type_f', 
#  '20210427_GPGAUSS_tot_sens_mv_res_True_inp_type_ret']



# ['20210427_GPGAUSS_tot_len_action_type_GP_activation_relu', 
#  '20210427_GPGAUSS_tot_len_action_type_GP_activation_tanh', 
#  '20210427_GPGAUSS_tot_len_action_type_MV_activation_relu', 
#  '20210427_GPGAUSS_tot_len_action_type_MV_activation_tanh']

# ['20210427_GPGAUSS_tot_sens_len_len_series_4000']

# ['20210427_GPGAUSS_tot_sens_len_len_series_2000','20210427_GPGAUSS_tot_sens_len_len_series_4000']


# ['20210427_GPGAUSS_tot_sens2_clip_param_0.2_gamma_0.5', 
#   '20210427_GPGAUSS_tot_sens2_clip_param_0.2_gamma_0.8', 
#   '20210427_GPGAUSS_tot_sens2_clip_param_0.4_gamma_0.3', 
#   '20210427_GPGAUSS_tot_sens2_clip_param_0.4_gamma_0.5', 
#   '20210427_GPGAUSS_tot_sens2_clip_param_0.4_gamma_0.8',
#   '20210427_GPGAUSS_tot_sens2_relu_clip_param_0.2_gamma_0.3', 
#   '20210427_GPGAUSS_tot_sens2_relu_clip_param_0.2_gamma_0.5', 
#   '20210427_GPGAUSS_tot_sens2_relu_clip_param_0.2_gamma_0.8', 
#   '20210427_GPGAUSS_tot_sens2_relu_clip_param_0.4_gamma_0.3', 
#   '20210427_GPGAUSS_tot_sens2_relu_clip_param_0.4_gamma_0.5', 
#   '20210427_GPGAUSS_tot_sens2_relu_clip_param_0.4_gamma_0.8']


 # ['20210426_GPGAUSS_tot_sens_lr_0.0001_ent_c_0.01_clip_param_0.2_batch_norm_value_out_False_gamma_0.5', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0001_ent_c_0.01_clip_param_0.2_batch_norm_value_out_False_gamma_0.8', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0001_ent_c_0.01_clip_param_0.2_batch_norm_value_out_True_gamma_0.5', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0001_ent_c_0.01_clip_param_0.2_batch_norm_value_out_True_gamma_0.8', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0001_ent_c_0.01_clip_param_0.4_batch_norm_value_out_False_gamma_0.5', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0001_ent_c_0.01_clip_param_0.4_batch_norm_value_out_False_gamma_0.8', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0001_ent_c_0.01_clip_param_0.4_batch_norm_value_out_True_gamma_0.5', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0001_ent_c_0.01_clip_param_0.4_batch_norm_value_out_True_gamma_0.8', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0001_ent_c_0.0_clip_param_0.2_batch_norm_value_out_False_gamma_0.5', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0001_ent_c_0.0_clip_param_0.2_batch_norm_value_out_False_gamma_0.8']
  
 # ['20210426_GPGAUSS_tot_sens_lr_0.0001_ent_c_0.0_clip_param_0.2_batch_norm_value_out_True_gamma_0.5', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0001_ent_c_0.0_clip_param_0.2_batch_norm_value_out_True_gamma_0.8', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0001_ent_c_0.0_clip_param_0.4_batch_norm_value_out_False_gamma_0.5', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0001_ent_c_0.0_clip_param_0.4_batch_norm_value_out_False_gamma_0.8', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0001_ent_c_0.0_clip_param_0.4_batch_norm_value_out_True_gamma_0.5', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0001_ent_c_0.0_clip_param_0.4_batch_norm_value_out_True_gamma_0.8', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0003_ent_c_0.01_clip_param_0.2_batch_norm_value_out_False_gamma_0.5', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0003_ent_c_0.01_clip_param_0.2_batch_norm_value_out_False_gamma_0.8', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0003_ent_c_0.01_clip_param_0.2_batch_norm_value_out_True_gamma_0.5', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0003_ent_c_0.01_clip_param_0.2_batch_norm_value_out_True_gamma_0.8', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0003_ent_c_0.01_clip_param_0.4_batch_norm_value_out_False_gamma_0.5', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0003_ent_c_0.01_clip_param_0.4_batch_norm_value_out_False_gamma_0.8', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0003_ent_c_0.01_clip_param_0.4_batch_norm_value_out_True_gamma_0.5', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0003_ent_c_0.01_clip_param_0.4_batch_norm_value_out_True_gamma_0.8', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0003_ent_c_0.0_clip_param_0.2_batch_norm_value_out_False_gamma_0.5', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0003_ent_c_0.0_clip_param_0.2_batch_norm_value_out_False_gamma_0.8', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0003_ent_c_0.0_clip_param_0.2_batch_norm_value_out_True_gamma_0.5', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0003_ent_c_0.0_clip_param_0.2_batch_norm_value_out_True_gamma_0.8', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0003_ent_c_0.0_clip_param_0.4_batch_norm_value_out_False_gamma_0.5', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0003_ent_c_0.0_clip_param_0.4_batch_norm_value_out_False_gamma_0.8', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0003_ent_c_0.0_clip_param_0.4_batch_norm_value_out_True_gamma_0.5', 
 # '20210426_GPGAUSS_tot_sens_lr_0.0003_ent_c_0.0_clip_param_0.4_batch_norm_value_out_True_gamma_0.8'] 

# ['20210418_GPGAUSS_tot_sens_n_train_{}_halflife_{}_sigmaf_{}_mv_res_False_inp_type_f', 
#   '20210418_GPGAUSS_tot_sens_n_train_{}_halflife_{}_sigmaf_{}_mv_res_False_inp_type_ret', 
#   '20210418_GPGAUSS_tot_sens_n_train_{}_halflife_{}_sigmaf_{}_mv_res_True_inp_type_f', 
#   '20210418_GPGAUSS_tot_sens_n_train_{}_halflife_{}_sigmaf_{}_mv_res_True_inp_type_ret',]


# ['20210418_GPGAUSS_tot_sens_n_train_{}_halflife_{}_sigmaf_{}_mv_res_False_inp_type_f']

# '20210418_GPGAUSS_tot_sens_n_train_{}_halflife_{}_sigmaf_{}_mv_res_{}_inp_type_{}'

# ['20210418_GPGAUSS_tot_sens_n_train_{}_halflife_{}_sigmaf_{}_mv_res_False_inp_type_f', 
#   '20210418_GPGAUSS_tot_sens_n_train_{}_halflife_{}_sigmaf_{}_mv_res_False_inp_type_ret', 
#   '20210418_GPGAUSS_tot_sens_n_train_{}_halflife_{}_sigmaf_{}_mv_res_True_inp_type_f', 
#   '20210418_GPGAUSS_tot_sens_n_train_{}_halflife_{}_sigmaf_{}_mv_res_True_inp_type_ret',]
hyperparams_model: null # ['250000', '2.5_126', '0.05_0.1']
hyperparams_exp: null # ['100000', '2.5_126', '0.05_0.1', 'False', 'f']




# ['20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_11_sigmaf_0.05_0.1_mv_res_False_inp_type_f', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_11_sigmaf_0.05_0.1_mv_res_False_inp_type_ret', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_11_sigmaf_0.05_0.1_mv_res_True_inp_type_f', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_11_sigmaf_0.05_0.1_mv_res_True_inp_type_ret', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_11_sigmaf_0.1_0.1_mv_res_False_inp_type_f', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_11_sigmaf_0.1_0.1_mv_res_False_inp_type_ret', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_11_sigmaf_0.1_0.1_mv_res_True_inp_type_f', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_11_sigmaf_0.1_0.1_mv_res_True_inp_type_ret', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_11_sigmaf_0.2_0.1_mv_res_False_inp_type_f', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_11_sigmaf_0.2_0.1_mv_res_False_inp_type_ret', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_11_sigmaf_0.2_0.1_mv_res_True_inp_type_f', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_11_sigmaf_0.2_0.1_mv_res_True_inp_type_ret', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_126_sigmaf_0.05_0.1_mv_res_False_inp_type_f', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_126_sigmaf_0.05_0.1_mv_res_False_inp_type_ret', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_126_sigmaf_0.05_0.1_mv_res_True_inp_type_f', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_126_sigmaf_0.05_0.1_mv_res_True_inp_type_ret', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_126_sigmaf_0.1_0.1_mv_res_False_inp_type_f', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_126_sigmaf_0.1_0.1_mv_res_False_inp_type_ret', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_126_sigmaf_0.1_0.1_mv_res_True_inp_type_f', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_126_sigmaf_0.1_0.1_mv_res_True_inp_type_ret', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_126_sigmaf_0.2_0.1_mv_res_False_inp_type_f', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_126_sigmaf_0.2_0.1_mv_res_False_inp_type_ret', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_126_sigmaf_0.2_0.1_mv_res_True_inp_type_f', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_2.5_126_sigmaf_0.2_0.1_mv_res_True_inp_type_ret', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_66_630_sigmaf_0.05_0.1_mv_res_False_inp_type_f', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_66_630_sigmaf_0.05_0.1_mv_res_False_inp_type_ret', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_66_630_sigmaf_0.05_0.1_mv_res_True_inp_type_f', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_66_630_sigmaf_0.05_0.1_mv_res_True_inp_type_ret', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_66_630_sigmaf_0.1_0.1_mv_res_False_inp_type_f', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_66_630_sigmaf_0.1_0.1_mv_res_False_inp_type_ret', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_66_630_sigmaf_0.1_0.1_mv_res_True_inp_type_f', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_66_630_sigmaf_0.1_0.1_mv_res_True_inp_type_ret', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_66_630_sigmaf_0.2_0.1_mv_res_False_inp_type_f', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_66_630_sigmaf_0.2_0.1_mv_res_False_inp_type_ret', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_66_630_sigmaf_0.2_0.1_mv_res_True_inp_type_f', 
#  '20210418_GPGAUSS_tot_sens_n_train_100000_halflife_66_630_sigmaf_0.2_0.1_mv_res_True_inp_type_ret']

#######################################################################
#  ['20210417_GPGAUSS_sens_mv_res_False_inp_type_f_sigmaf_0.2_0.1',
#  '20210417_GPGAUSS_sens_mv_res_False_inp_type_ret_sigmaf_0.2_0.1',
# '20210417_GPGAUSS_sens_mv_res_False_inp_type_f_sigmaf_0.1_0.1',
#  '20210417_GPGAUSS_sens_mv_res_False_inp_type_ret_sigmaf_0.1_0.1',]



#  ['20210417_GPGAUSS_sens_mv_res_False_inp_type_f_sigmaf_0.1_0.1', 
#  '20210417_GPGAUSS_sens_mv_res_False_inp_type_f_sigmaf_0.2_0.1', 
#  '20210417_GPGAUSS_sens_mv_res_False_inp_type_ret_sigmaf_0.1_0.1', 
#  '20210417_GPGAUSS_sens_mv_res_False_inp_type_ret_sigmaf_0.2_0.1', 
#  '20210417_GPGAUSS_sens_mv_res_True_inp_type_f_sigmaf_0.1_0.1', 
# '20210417_GPGAUSS_sens_mv_res_True_inp_type_f_sigmaf_0.2_0.1', 
#  '20210417_GPGAUSS_sens_mv_res_True_inp_type_ret_sigmaf_0.1_0.1', 
#  '20210417_GPGAUSS_sens_mv_res_True_inp_type_ret_sigmaf_0.2_0.1']


# ['20210417_GPGAUSS_mv_res_False_inp_type_f', 
# '20210417_GPGAUSS_mv_res_False_inp_type_ret', 
# '20210417_GPGAUSS_mv_res_True_inp_type_f', 
# '20210417_GPGAUSS_mv_res_True_inp_type_ret']


# ['20210417_GPGAUSS_mv_res_False_inp_type_f', 
# '20210417_GPGAUSS_mv_res_False_inp_type_ret', 
# '20210417_GPGAUSS_mv_res_True_inp_type_f', 
# '20210417_GPGAUSS_mv_res_True_inp_type_ret']

