# Flags for operate different tests
algo : 'Q' # Q-Ritter: experiment from Ritter(2017), Qlin
# Parameter for the QLearning implementation of Ritter
epsilon : 0.1  # greedy policy choice
alpha : 0.001 # discounting factor for the Q updating error (learning rate)
gamma : 0.999 # discounting factor for the Q target (sort of interest rate)
kappa : 0.0001 # risk aversion
HalfLife : [5,206,700] # half-life of mean reversion to compute speed of mean reversion for the 3 factors
f_init : [0,0,0] # initial values for simulating factors
f_param : [0.0005,0.000131,-0.0008250] # regression parameters for factors [10.32,122.34,-205.59]
sigma  : 0.2 # return volatility
sigmaf : 0.08 # factors volatility
P_min  : 1 # boundaries of the price
P_max  : 1000
P_e    : 50 # equilibrium price
LotSize  : 50 # minimum size of tradable (equities/contracts)
K  : 600 # actions that each trade can take: from -K to +K lot sizes
M  : 1000 # multiple of lot Sizes than the total portfolio can hold
TickSize  : 0.1 # minimum price movement of a trading instrument
N_train : 1000000 # training steps (each step consists of one action-value update)
TestSteps: 5000 # Out-of-sample simulated price for testing
plot_inputs : 0 # boolean for plotting prices,ret and factors of out-of-sample testing
##########################################################################################################
# Parameter for extending the framework
CostMultiplier: 0.1 # Cost multiplier to make the cost proportional to the risk as in Gar Ped (2013)
                          # It is chosen as the median across the estimate of CM for each asset
DiscountRate: 0.02 # discount rate as in the paper
Seed: 42 # Seed for experiment reproducibility
RollingMean: False # Flag for calculating the rolling mean of expected returns
LenRollMean: 66 # Lenght of the rolling mean of expected returns (default 3 months)
##########################################################################################################
# Parameter for storing results
outputDir: 'GP'
##########################################################################################################
# Parameter for plotting results
holding: 0 # set holding to visualize
Aggregation: 1 # flag for aggregation by holding
##########################################################################################################
# Parameter for linear q-function approximation